/** Emits dist/tokens.css from the same raw palette the StyleX variables use,
    so CSS-only consumers (packages/web-ui, apps/angular-web) can share one
    source of truth. Run by `bun run build` in this package. */
import { mkdirSync, writeFileSync } from "node:fs";
import { dark, light, type TokenSet } from "../src/tokens";
import { fonts } from "../src/fonts";

export const kebab = (camel: string) => camel.replace(/[A-Z0-9]+/g, (m) => `-${m.toLowerCase()}`);

function block(selector: string, tokens: TokenSet, extra = ""): string {
  const lines = Object.entries(tokens).map(([k, v]) => `  --${kebab(k)}: ${v};`);
  return `${selector} {\n${lines.join("\n")}\n${extra}}\n`;
}

const css = [
  "/* Generated by packages/design-tokens/scripts/emit-css.ts — do not edit. */",
  block(
    ":root",
    dark,
    `  --font-sans: ${fonts.sans};\n  --font-mono: ${fonts.mono};\n  --font-display: ${fonts.display};\n  color-scheme: dark;\n`,
  ),
  block('[data-theme="light"]', light, "  color-scheme: light;\n"),
].join("\n");

mkdirSync(new URL("../dist/", import.meta.url), { recursive: true });
writeFileSync(new URL("../dist/tokens.css", import.meta.url), css);
console.log(`design-tokens: wrote dist/tokens.css (${css.length} bytes)`);
