/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedHiringProcessesIndexRouteImport } from './routes/_authenticated/hiring-processes/index'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedHiringProcessesNewRouteImport } from './routes/_authenticated/hiring-processes/new'
import { Route as AuthenticatedHiringProcessesIdRouteImport } from './routes/_authenticated/hiring-processes/$id'
import { Route as AuthenticatedHiringProcessesIdEditRouteImport } from './routes/_authenticated/hiring-processes/$id_.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHiringProcessesIndexRoute =
  AuthenticatedHiringProcessesIndexRouteImport.update({
    id: '/hiring-processes/',
    path: '/hiring-processes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHiringProcessesNewRoute =
  AuthenticatedHiringProcessesNewRouteImport.update({
    id: '/hiring-processes/new',
    path: '/hiring-processes/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHiringProcessesIdRoute =
  AuthenticatedHiringProcessesIdRouteImport.update({
    id: '/hiring-processes/$id',
    path: '/hiring-processes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHiringProcessesIdEditRoute =
  AuthenticatedHiringProcessesIdEditRouteImport.update({
    id: '/hiring-processes/$id_/edit',
    path: '/hiring-processes/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/hiring-processes/$id': typeof AuthenticatedHiringProcessesIdRoute
  '/hiring-processes/new': typeof AuthenticatedHiringProcessesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/hiring-processes': typeof AuthenticatedHiringProcessesIndexRoute
  '/hiring-processes/$id/edit': typeof AuthenticatedHiringProcessesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/hiring-processes/$id': typeof AuthenticatedHiringProcessesIdRoute
  '/hiring-processes/new': typeof AuthenticatedHiringProcessesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/hiring-processes': typeof AuthenticatedHiringProcessesIndexRoute
  '/hiring-processes/$id/edit': typeof AuthenticatedHiringProcessesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/_authenticated/hiring-processes/$id': typeof AuthenticatedHiringProcessesIdRoute
  '/_authenticated/hiring-processes/new': typeof AuthenticatedHiringProcessesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/_authenticated/hiring-processes/': typeof AuthenticatedHiringProcessesIndexRoute
  '/_authenticated/hiring-processes/$id_/edit': typeof AuthenticatedHiringProcessesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/hiring-processes/$id'
    | '/hiring-processes/new'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/hiring-processes'
    | '/hiring-processes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/hiring-processes/$id'
    | '/hiring-processes/new'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/hiring-processes'
    | '/hiring-processes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth/login'
    | '/auth/signup'
    | '/_authenticated/hiring-processes/$id'
    | '/_authenticated/hiring-processes/new'
    | '/api/auth/$'
    | '/api/v1/$'
    | '/_authenticated/hiring-processes/'
    | '/_authenticated/hiring-processes/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hiring-processes/': {
      id: '/_authenticated/hiring-processes/'
      path: '/hiring-processes'
      fullPath: '/hiring-processes'
      preLoaderRoute: typeof AuthenticatedHiringProcessesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hiring-processes/new': {
      id: '/_authenticated/hiring-processes/new'
      path: '/hiring-processes/new'
      fullPath: '/hiring-processes/new'
      preLoaderRoute: typeof AuthenticatedHiringProcessesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hiring-processes/$id': {
      id: '/_authenticated/hiring-processes/$id'
      path: '/hiring-processes/$id'
      fullPath: '/hiring-processes/$id'
      preLoaderRoute: typeof AuthenticatedHiringProcessesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hiring-processes/$id_/edit': {
      id: '/_authenticated/hiring-processes/$id_/edit'
      path: '/hiring-processes/$id/edit'
      fullPath: '/hiring-processes/$id/edit'
      preLoaderRoute: typeof AuthenticatedHiringProcessesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHiringProcessesIdRoute: typeof AuthenticatedHiringProcessesIdRoute
  AuthenticatedHiringProcessesNewRoute: typeof AuthenticatedHiringProcessesNewRoute
  AuthenticatedHiringProcessesIndexRoute: typeof AuthenticatedHiringProcessesIndexRoute
  AuthenticatedHiringProcessesIdEditRoute: typeof AuthenticatedHiringProcessesIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHiringProcessesIdRoute: AuthenticatedHiringProcessesIdRoute,
  AuthenticatedHiringProcessesNewRoute: AuthenticatedHiringProcessesNewRoute,
  AuthenticatedHiringProcessesIndexRoute:
    AuthenticatedHiringProcessesIndexRoute,
  AuthenticatedHiringProcessesIdEditRoute:
    AuthenticatedHiringProcessesIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
